apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-events-rolebinding
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard  # Adjust namespace if needed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-events-role
